pipeline{
    
    agent any
    stages{
        
            stage('Compile stage'){
            
                    steps{
                            bat 'mvn -f Onlinebookstoresystem-master/pom.xml install'
                    }

                }
        
            stage('Test Stage'){
        
                    steps{
                            script{
                                    try{
                                            bat 'mvn -f Onlinebookstore/pom.xml install'
                                    }catch(err){
                                                    echo err.getMessage()
                                    }
                         }

                    }
              }
        
            stage('Sonar analysis'){
                    
                    steps{
                            script {        
                                        withSonarQubeEnv('Sonar'){   
                        
                                        bat 'mvn -f Onlinebookstore/pom.xml sonar:sonar -Dsonar.login=admin -Dsonar.password=admin'
                     
                                    }
                            }
        
                     }
                }    
        
            stage("Quality Gate"){
                                    steps{
                                            script{
                                                    timeout(time: 1, unit: 'HOURS') {
                                                    try{
                                                            def qg = waitForQualityGate() // Reuse taskId previously collected by withSonarQubeEnv
                                                            if (qg.status != 'OK') {
                                                                error "Pipeline aborted due to quality gate failure: ${qg.status}"
                                                            }
                                                            else
                                                            {
                                                                emailext attachLog: true, body: 'Unit test cases passing percentage criteria matched', recipientProviders: [developers()], subject: 'Build success', to: 'marathemayuresh92@gmail.com'                
                                                                
                                                            }
                       
                                                        }catch(err){
                                                                        echo err.getMessage()
                                                                        emailext attachLog: true, body: 'Unit test cases passing percentage criteria not matched', recipientProviders: [developers()], subject: 'Build success', to: 'marathemayuresh92@gmail.com'                
                                                        }
                       
                                                    }
            
                                                }
        
                                        }
        
                                }
        
                    
                }

         }   
